Hamburgueria/Models/Produtos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamburgueria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.ProdutosDosPedidos = new HashSet<ProdutosDosPedidos>();
        }
    
        public int Id { get; set; }
        public int IdTipoDoProduto { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public string Descricao { get; set; }
        public string Imagem { get; set; }
    
        public virtual TiposDeProdutos TiposDeProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosDosPedidos> ProdutosDosPedidos { get; set; }
    }
}

Hamburgueria/Controllers/ProdutosController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Hamburgueria.Models;
using System.Web;
using System.IO;
using System;
using System.Data;
using Hamburgueria.Filtros;

namespace Hamburgueria.Controllers
{
    [SomenteAdminLogado]
    public class ProdutosController : AutenticacaoController
    {
        // GET: Produtos
        public ActionResult Index()
        {
            var produtos = db.Produtos.Include(p => p.TiposDeProdutos);
            return View(produtos.ToList());
        }

        // GET: Produtos/Details/5
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produtos produtos = db.Produtos.Find(id);
            if (produtos == null)
            {
                return HttpNotFound();
            }
            return View(produtos);
        }

        // GET: Produtos/Cadastrar
        public ActionResult Criar()
        {
            ViewBag.IdTipoDoProduto = new SelectList(db.TiposDeProdutos, "Id", "Nome");
            Produtos model = new Produtos();
            return View(model);
        }

        // POST: Produtos/Cadastrar
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar([Bind(Include = "IdTipoDoProduto,Nome,Preco,Descricao")] Produtos produtos, HttpPostedFileBase image)
        {
            try
            {
                if (image.FileName == string.Empty & image.ContentLength == 0)
                {
                    throw new FileNotFoundException("Imagem não encontrada no caminho especifiado. Informe um caminho válido");
                }

                string tipoDoProduto = db.TiposDeProdutos.Where(x => x.Id == produtos.IdTipoDoProduto).Select(x => x.Nome).FirstOrDefault();
                produtos.Imagem = string.Concat(produtos.Nome, " - ", tipoDoProduto, Path.GetExtension(image.FileName));
                string caminho = Path.Combine(Server.MapPath("~/Img/produtos/") + produtos.Imagem);

                if (System.IO.File.Exists(caminho))
                {
                    throw new ConstraintException(@"Já existe um produto do tipo <i>" + tipoDoProduto + "</i> cadastrado com o nome " + produtos.Nome +
                                ".<p>Delete o produto anterior ou clique em alterar</p>");
                }
                if (ModelState.IsValid)
                {
                    image.SaveAs(caminho);
                    db.Produtos.Add(produtos);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (FileNotFoundException e)
            {
                TempData["MensagemErro"] = e.Message;
            }
            catch (ConstraintException e)
            {
                TempData["MensagemErro"] = e.Message;
            }
            catch (Exception e)
            {

                string tipoDoProduto = db.TiposDeProdutos.Where(x => x.Id == produtos.IdTipoDoProduto).Select(x => x.Nome).FirstOrDefault();
                produtos.Imagem = string.Concat(produtos.Nome, " - ", tipoDoProduto, Path.GetExtension(image.FileName));
                string caminho = Path.Combine(Server.MapPath("~/Img/produtos/") + produtos.Imagem);

                if (System.IO.File.Exists(caminho))
                    System.IO.File.Delete(caminho);

                TempData["MensagemErro"] = "Erro ao tentar criar novo produto. Código do erro:" + e.HResult;
            }

            ViewBag.IdTipoDoProduto = new SelectList(db.TiposDeProdutos, "Id", "Nome", produtos.IdTipoDoProduto);
            return View(produtos);
        }

        // GET: Produtos/Edit/5
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produtos produtos = db.Produtos.Find(id);
            if (produtos == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTipoDoProduto = new SelectList(db.TiposDeProdutos, "Id", "Nome", produtos.IdTipoDoProduto);
            return View(produtos);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Id,IdTipoDoProduto,Nome,Preco,Descricao")] Produtos produtos, HttpPostedFileBase image)
        {
            try
            {
                if (image.FileName == string.Empty & image.ContentLength == 0)
                {
                    throw new FileNotFoundException("Imagem não encontrada no caminho especifiado. Informe um caminho válido");
                }

                string tipoDoProduto = db.TiposDeProdutos.Where(x => x.Id == produtos.IdTipoDoProduto).Select(x => x.Nome).FirstOrDefault();
                produtos.Imagem = string.Concat(produtos.Nome, " - ", tipoDoProduto, Path.GetExtension(image.FileName));
                string caminho = Path.Combine(Server.MapPath("~/Img/produtos/") + produtos.Imagem);

                if (System.IO.File.Exists(caminho))
                {
                    if (System.IO.File.Exists(caminho))
                        System.IO.File.Delete(caminho);
                }
                if (ModelState.IsValid)
                {
                    image.SaveAs(caminho);
                    db.Entry(produtos).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (FileNotFoundException e)
            {
                TempData["MensagemErro"] = e.Message;
            }
            catch (ConstraintException e)
            {
                TempData["MensagemErro"] = e.Message;
            }
            catch (Exception e)
            {

                string tipoDoProduto = db.TiposDeProdutos.Where(x => x.Id == produtos.IdTipoDoProduto).Select(x => x.Nome).FirstOrDefault();
                produtos.Imagem = string.Concat(produtos.Nome, " - ", tipoDoProduto, Path.GetExtension(image.FileName));
                string caminho = Path.Combine(Server.MapPath("~/Img/produtos/") + produtos.Imagem);

                if (System.IO.File.Exists(caminho))
                    System.IO.File.Delete(caminho);

                TempData["MensagemErro"] = "Erro ao tentar criar novo produto. Código do erro:" + e.HResult;
            }

            ViewBag.IdTipoDoProduto = new SelectList(db.TiposDeProdutos, "Id", "Nome", produtos.IdTipoDoProduto);
            return View(produtos);
        }

        // GET: Produtos/Delete/5
        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produtos produtos = db.Produtos.Find(id);
            if (produtos == null)
            {
                return HttpNotFound();
            }
            return View(produtos);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produtos produtos = db.Produtos.Find(id);
            db.Produtos.Remove(produtos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hamburgueria/Views/Produtos/Criar.cshtml
@model Hamburgueria.Models.Produtos

@{
    ViewBag.Title = "Novo produto";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Novo Produto</h2>

@using (Html.BeginForm("Criar", "Produtos", FormMethod.Post, new { enctype = "multipart/form-data", @class = "upload-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produtos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDoProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDoProduto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDoProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control dinheiro" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-12" style="color: indianred; padding-left: 18%;">Atenção: Imagens de no máximo 2Mb nos formatos PNG ou JPG</p>
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="upload-file" data-max-size="2097152" name="image" id="image">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="enviar-formulario" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hamburgueria/Views/Produtos/Deletar.cshtml
@model Hamburgueria.Models.Produtos

@{
    ViewBag.Title = "Deletar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Deletar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TiposDeProdutos.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TiposDeProdutos.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à lista", "Index")
        </div>
    }
</div>

Hamburgueria/Views/Produtos/Detalhes.cshtml
@model Hamburgueria.Models.Produtos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TiposDeProdutos.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TiposDeProdutos.Nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar à lista", "Index")
</p>

Hamburgueria/Views/Produtos/Editar.cshtml
@model Hamburgueria.Models.Produtos

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Produtos", FormMethod.Post, new { enctype = "multipart/form-data", @class = "upload-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produtos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <img src="~/Img/produtos/@Model.Imagem" style="margin-left: 30%; margin-bottom: 50px; width: 50%; border-radius: 6%;"/>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoDoProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoDoProduto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoDoProduto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control dinheiro" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-12" style="color: indianred; padding-left: 18%;">Atenção: Imagens de no máximo 2Mb nos formatos PNG ou JPG</p>
            <label class="control-label col-md-2" for="Imagem">Trocar imagem</label>
            <div class="col-md-10">
                <input type="file" class="upload-file" data-max-size="2097152" name="image" id="image">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="enviar-formulario" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

Hamburgueria/Views/Produtos/Index.cshtml
@model IEnumerable<Hamburgueria.Models.Produtos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Produtos</h2>

<p>
    @Html.ActionLink("Criar novo", "Criar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imagem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TiposDeProdutos.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Imagem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TiposDeProdutos.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Detalhes", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "Deletar", new { id=item.Id })
        </td>
    </tr>
}

</table>