Hamburgueria/Models/Usuarios.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamburgueria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Enderecos = new HashSet<Enderecos>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int Id { get; set; }
        public int IdTiposDeUsuarios { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataDeNascimento { get; set; }
        public bool DesejaReceberEmail { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enderecos> Enderecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual TiposDeUsuarios TiposDeUsuarios { get; set; }
    }
}

Hamburgueria/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using Arcnet.MyConvert;
using System.Web.Mvc;
using Hamburgueria.Models;
using Hamburgueria.Filtros;

namespace Hamburgueria.Controllers
{
    public class UsuariosController : AutenticacaoController
    {
        // GET: Usuarios
        [SomenteAdminLogado]
        public ActionResult Index()
        {
            var usuarios = db.Usuarios.Include(u => u.TiposDeUsuarios);
            return View(usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        [SomenteAdminLogado]
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }
            return View(usuarios);
        }

        // GET: Usuarios/Create
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(string Usuario, string Senha, string Nome, DateTime DataDeNascimento, bool DesejaReceberEmail, string Email, string confirmaSenha)
        {
            //Por algum motivo, o Bind não deu certo e tive que fazer assim... se for arrumar, lembre-se que o id do tipo de 
            //usuário não é passado no formulário como hidden field então tem que setar como 4 aqui no controller
            Usuarios usuario = new Usuarios()
            {
                Usuario = Usuario,
                Senha = Senha,
                Nome = Nome,
                DataDeNascimento = DataDeNascimento,
                DesejaReceberEmail = DesejaReceberEmail,
                Email = Email,
                IdTiposDeUsuarios = 4
            };
            try
            {

                if (usuario.Senha != confirmaSenha)
                {
                    TempData["MensagemErro"] = "As senhas não conferem.";
                    return View(usuario);

                }
                else if (db.Usuarios.Where(u => u.Email == usuario.Email).Count() != 0)
                {
                    TempData["MensagemErro"] = "Email já cadastrado. Tente usar um diferente. Caso já tenha uma conta e não se lembre dos dados, vá em \"Esqueci minha senha\"";
                    return View(usuario);
                }
                else if (db.Usuarios.Where(u => u.Usuario == usuario.Usuario).Count() != 0)
                {
                    TempData["MensagemErro"] = "Usuário já cadastrado. Tente usar um diferente. Caso já tenha uma conta e não se lembre dos dados, vá em \"Esqueci minha senha\"";
                    return View(usuario);
                }
                else if (ModelState.IsValid)
                {
                    usuario.Senha = MyConvert.ToMd5(usuario.Senha);
                    db.Usuarios.Add(usuario);
                    db.SaveChanges();
                    DadosTemporarios.ArmazenaUsuario(usuario);
                    DadosTemporarios.ArmazenaNivelDeAcessoDoUsuario("Cliente");
                    DadosTemporarios.ArmazenaEmailDoUsuario(usuario.Email);
                    return RedirectToAction("Cadastrar", "Enderecos");
                }
                return View(usuario);
            }
            catch
            {
                TempData["MensagemErro"] = "Parece que algo deu errado. Tente mais tarde. Se o problema persistir, ligue para gente ou " +
                    "entre em contato pelo \"Fale conosco\"";
                return RedirectToAction("Index", "Home");
            }


        }

        [HttpGet]
        [SomenteClienteLogado]
        public ActionResult Editar()
        {
            int id = DadosTemporarios.RetornaUsuario().Id;
            Usuarios usuarios = db.Usuarios.Find(id);
            if (usuarios == null)
            {
                return HttpNotFound();
            }

            if (DadosTemporarios.RetornaUsuario().Id == id)
            {
                return View(usuarios);
            }
            else
            {
                TempData["MensagemErro"] = "Não é possível editar dados de outro usuário além do seu.";
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [SomenteClienteLogado]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Id,IdTiposDeUsuarios,Senha,Usuario,Nome,DataDeNascimento,DesejaReceberEmail,Email")] Usuarios usuarios)
        {
            try
            {
                if (usuarios.Usuario != DadosTemporarios.RetornaUsuario().Usuario && db.Usuarios.Where(u => u.Usuario == usuarios.Usuario).FirstOrDefault() != null)
                {
                    TempData["MensagemErro"] = "Não foi possível editar dados do seu usuário pois já existe um usuário com o mesmo nome no sistema.";
                    return RedirectToAction("Index", "Home");
                }

                if (usuarios.Email != DadosTemporarios.RetornaUsuario().Email && db.Usuarios.Where(u => u.Email == usuarios.Email).FirstOrDefault() != null)
                {
                    TempData["MensagemErro"] = "Não foi possível editar dados do seu usuário pois já existe um usuário com o mesmo nome no sistema.";
                    return RedirectToAction("Index", "Home");
                }

                usuarios.IdTiposDeUsuarios = 4;
                if (ModelState.IsValid)
                {
                    db.Entry(usuarios).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["MensagemErro"] = "Parece que algo deu errado no envio do formulário";
                    return View("Editar");
                }

            }
            catch (Exception e)
            {
                TempData["MensagemErro"] = "Parece que algo deu errado. Tente novamente mais tarde";
                return View("Editar");
            }
        }

        [HttpPost]
        [SomenteClienteLogado]
        public ActionResult AlterarSenha(string senha, string novaSenha, string repetirSenha)
        {
            try
            {
                Usuarios usuario = DadosTemporarios.RetornaUsuario();
                if (usuario.Senha == MyConvert.ToMd5(senha))
                {
                    if (novaSenha != repetirSenha)
                    {
                        TempData["MensagemErro"] = "As senhas não conferem. Tente novamente";
                        return View("Editar");
                    }
                    usuario.Senha = MyConvert.ToMd5(novaSenha);
                    db.Usuarios.Update(usuario);
                    db.SaveChanges();
                    TempData["MensagemSucesso"] = "Senha alterada com sucesso";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["MensagemErro"] = "Senha incorreta. Tente novamente";
                    return View("Editar");
                }
            }
            catch
            {
                TempData["MensagemErro"] = "Parece que algo deu errado. Tente novamente mais tarde";
                return View("Editar");
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hamburgueria/Views/Usuarios/Cadastrar.cshtml
@model Hamburgueria.Models.Usuarios

@{
    ViewBag.Title = "Cadastrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
COLOCAR AQUI STEPS (1º PASSO, 2º PASSO...)
<br/>
<h2>Cadastrar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Senha, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Senha">Confirme sua senha</label>
            <div class="col-md-10">
                <input class="form-control" data-val="true" data-val-required="O campo Usuário é obrigatório." id="confirmaSenha" name="confirmaSenha" type="password">
                <span class="field-validation-valid text-danger" data-valmsg-for="Senha" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DesejaReceberEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DesejaReceberEmail)
                    @Html.ValidationMessageFor(model => model.DesejaReceberEmail, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Próximo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Hamburgueria/Views/Usuarios/Detalhes.cshtml
@model Hamburgueria.Models.Usuarios

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DesejaReceberEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesejaReceberEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TiposDeUsuarios.TipoDeUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TiposDeUsuarios.TipoDeUsuario)
        </dd>


        @* Lembrar de colocar um foreach para puxar os endereços da conta *@

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar à lista", "Index")
</p>

Hamburgueria/Views/Usuarios/Editar.cshtml
@model Hamburgueria.Models.Usuarios

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Usuarios", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-6">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DesejaReceberEmail, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-6">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DesejaReceberEmail)
                    @Html.ValidationMessageFor(model => model.DesejaReceberEmail, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @Html.HiddenFor(x => x.Senha)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("AlterarSenha", "Usuarios", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-6">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("senha", "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nova senha", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("novaSenha", "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Repita sua nova senha", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("repetirSenha", "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @Html.HiddenFor(x => x.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    
    </div>
}

Hamburgueria/Views/Usuarios/Index.cshtml
@model IEnumerable<Hamburgueria.Models.Usuarios>

@{
    ViewBag.Title = "Usuário cadastrados";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Lista de usuários cadastrados</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DesejaReceberEmail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td><!--  hidden for, Felipe! -->
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DesejaReceberEmail)
        </td>
        <td>
            @Html.ActionLink("Detalhes", "Detalhes", new { id=item.Id }) |
        </td>
    </tr>
}

</table>